version: "3.8"
services:
  frontend:
    container_name: frontend
    restart: always
    build:
      context: .
      dockerfile: frontend/react/imdb/Dockerfile
    ports:
      - "3001:3000"
  backend:
    restart: always
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8081:8081"
    environment:
      DB_URL: root:pass@tcp(database:3306)/test?parseTime=true

  database:
    image: mysql:8.0.30
    restart: always
    environment:
      MYSQL_DATABASE: 'test'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'pass'
      MYSQL_ROOT_PASSWORD: 'pass'
    ports:
      - '3307:3306'

volumes:
  db:
    driver: local