version: "3.8"
services:
  frontend:
    container_name: frontend
    restart: always
    build:
      context: ./frontend/react/imdb
      dockerfile: ./Dockerfile
    ports:
      - "3001:3000"
  backend:
    container_name: backend
    restart: always
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    ports:
      - "8082:8081"
    environment:
      DB_URL: root:pass@tcp(database:3306)/test?parseTime=true
  database:
    image: mysql:8.0.30
    restart: always
    environment:
      MYSQL_DATABASE: 'test'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'pass'
      MYSQL_ROOT_PASSWORD: 'pass'
    ports:
      - '3307:3306'

volumes:
  db:
    driver: local